[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss11"

    [buildPlans.IosevkaCustom.variants.design]
    tilde = "low"
    asterisk = "turn-hex-low"

    [buildPlans.IosevkaCustom.variants.italic]
    tilde = "low"

    [buildPlans.IosevkaCustom.variants.oblique]
    tilde = "low"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "haskell"

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 600
menu = 5
css = "normal"
